# Generated by Django 4.1.4 on 2022-12-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oilasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Oilasi',
                'verbose_name_plural': 'Oilalari',
            },
        ),
        migrations.CreateModel(
            name='Osimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('maqomi', models.TextField()),
                ('tavsif', models.TextField()),
                ('tarqalishi', models.TextField()),
                ('sharoiti', models.TextField()),
                ('soni', models.TextField()),
                ('kupayishi', models.CharField(max_length=255)),
                ('ozgarish_sabablari', models.TextField()),
                ('madaniylashtirish', models.TextField()),
                ('muhofaza_choralari', models.TextField()),
                ('img', models.ImageField(default='', upload_to='nature/')),
                ('oilasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmap.oilasi')),
            ],
            options={
                'verbose_name': "O'simlik",
                'verbose_name_plural': "O'simliklar",
            },
        ),
        migrations.CreateModel(
            name='Hayvon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('yili', models.IntegerField(default=2000)),
                ('maqomi', models.TextField()),
                ('tarqalishi', models.TextField()),
                ('yashash_joylari', models.TextField()),
                ('soni', models.TextField()),
                ('yashash_tarzi', models.TextField()),
                ('cheklovchi_omillar', models.TextField()),
                ('kupaytirish', models.CharField(max_length=255)),
                ('choralari', models.TextField()),
                ('img', models.ImageField(default='', upload_to='nature/')),
                ('oilasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmap.oilasi')),
            ],
            options={
                'verbose_name': 'Hayvon',
                'verbose_name_plural': 'Hayvonlar',
            },
        ),
        migrations.CreateModel(
            name='CoordinateOsimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[['Xorazm', 'Xorazm'], ['Andijan', 'Andijon'], ['Surxondaryo', 'Surxondaryo'], ['Buxoro', 'Buxoro'], ['Toshkent', 'Toshkent'], ['Navoiy', 'Navoiy'], ['Fargona', "Farg'ona"], ['Nukus', 'Nukus'], ['Jizzax', 'Jizzax'], ['Qarshi', 'Qarshi'], ['Namangan', 'Namangan'], ['Samarkand', 'Samarkand'], ['Sirdaryo', 'Sirdaryo']], max_length=20)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmap.osimlik')),
            ],
            options={
                'verbose_name': "Kordinata O'simlik",
                'verbose_name_plural': "Kordinatalar O'simliklar",
            },
        ),
        migrations.CreateModel(
            name='CoordinateHayvon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[['Xorazm', 'Xorazm'], ['Andijan', 'Andijon'], ['Surxondaryo', 'Surxondaryo'], ['Buxoro', 'Buxoro'], ['Toshkent', 'Toshkent'], ['Navoiy', 'Navoiy'], ['Fargona', "Farg'ona"], ['Nukus', 'Nukus'], ['Jizzax', 'Jizzax'], ['Qarshi', 'Qarshi'], ['Namangan', 'Namangan'], ['Samarkand', 'Samarkand'], ['Sirdaryo', 'Sirdaryo']], max_length=20)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmap.hayvon')),
            ],
            options={
                'verbose_name': 'Kordinata Hayvon',
                'verbose_name_plural': 'Kordinatalar Hayvon',
            },
        ),
    ]
